name: Update Bluesky Stats from Jazco

on:
  schedule:
    - cron: "0 1 * * *" # Daily at 01:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install requests pandas

      - name: Fetch and Append Data
        run: |
          mkdir -p docs/data
          python scripts/update_data.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/stats.json
          git commit -m "chore(stats): appends daily total_users from jazco.io" || echo "No changes to commit"
          git push
